"""
chatbot/intent_router.py
Routes extracted intents to the appropriate backend service.
"""
import logging
import datetime
from chatbot import model_services
from chatbot import sql_service
from chatbot import rag_service
from chatbot import parameter_resolver

logger = logging.getLogger("chatbot")

def route(intent_data: dict, original_query: str) -> dict:
    """
    Route the intent dict to the correct backend service.
    Returns: {success, ...tool_specific_data...}
    """
    intent = intent_data.get("intent")
    params = intent_data.get("parameters", {})
    
    # ─── DATA_QUERY ────────────────────────────────────────────────────────
    if intent == "DATA_QUERY":
        sql = params.get("sql_query")
        if not sql:
            return {"success": False, "error": "No SQL query generated by extractor."}
        result = sql_service.execute_safe_query(sql)
        result["tool_used"] = "SQL Analytics"
        result["intent"] = intent
        return result
        
    # ─── FARE_PREDICTION ───────────────────────────────────────────────────
    elif intent == "FARE_PREDICTION":
        oz_raw = params.get("origin_zone") or "JFK Airport"
        dz_raw = params.get("dest_zone") or "Times Square"
        oz = parameter_resolver.resolve_zone(oz_raw) or "JFK Airport"
        dz = parameter_resolver.resolve_zone(dz_raw) or "Times Sq/Theatre District"
        
        # Default to evening (18) if time is missing but we decided not to clarify
        hour = parameter_resolver.resolve_hour(params.get("time")) or 18
        
        # Default to today if date isn't specified
        date_str = parameter_resolver.resolve_date(params.get("date")) or datetime.date.today().strftime("%Y-%m-%d")
        dow = parameter_resolver.get_dow(date_str) or 5
        month = parameter_resolver.get_month(date_str) or 9
        
        result = model_services.predict_fare(oz, dz, hour, dow, month)
        result["tool_used"] = "Fare Model"
        result["intent"] = intent
        return result
        
    # ─── DURATION_PREDICTION ───────────────────────────────────────────────
    elif intent == "DURATION_PREDICTION":
        oz_raw = params.get("origin_zone") or "JFK Airport"
        dz_raw = params.get("dest_zone") or "Times Square"
        oz = parameter_resolver.resolve_zone(oz_raw) or "JFK Airport"
        dz = parameter_resolver.resolve_zone(dz_raw) or "Times Sq/Theatre District"
        hour = parameter_resolver.resolve_hour(params.get("time")) or 18
        date_str = parameter_resolver.resolve_date(params.get("date")) or datetime.date.today().strftime("%Y-%m-%d")
        dow = parameter_resolver.get_dow(date_str) or 5
        
        result = model_services.predict_duration(oz, dz, hour, dow)
        result["tool_used"] = "Duration Model"
        result["intent"] = intent
        return result
        
    # ─── DEMAND_FORECAST ───────────────────────────────────────────────────
    elif intent == "DEMAND_FORECAST":
        tz_raw = params.get("target_zone") or "Midtown Center"
        tz = parameter_resolver.resolve_zone(tz_raw) or "Midtown Center"
        hour = parameter_resolver.resolve_hour(params.get("time")) or 8
        date_str = parameter_resolver.resolve_date(params.get("date")) or (datetime.date.today() + datetime.timedelta(days=1)).strftime("%Y-%m-%d") # tomorrow normally
        
        result = model_services.forecast_demand(tz, date_str, hour)
        result["tool_used"] = "Demand Model"
        result["intent"] = intent
        return result
        
    # ─── ZONE_CLUSTERING ───────────────────────────────────────────────────
    elif intent == "ZONE_CLUSTERING":
        tz_raw = params.get("target_zone") or "East Village"
        tz = parameter_resolver.resolve_zone(tz_raw) or "East Village"
             
        result = model_services.classify_zone(tz)
        result["tool_used"] = "Clustering Model"
        result["intent"] = intent
        return result
        
    # ─── RAG_KNOWLEDGE ─────────────────────────────────────────────────────
    elif intent == "RAG_KNOWLEDGE":
        result = rag_service.retrieve_knowledge(original_query)
        result["tool_used"] = "Documentation RAG"
        result["intent"] = intent
        return result
        
    # ─── COMBINED_QUERY ────────────────────────────────────────────────────
    elif intent == "COMBINED_QUERY":
        sql = params.get("sql_query")
        rag_result = rag_service.retrieve_knowledge(original_query)
        
        if sql:
            sql_result = sql_service.execute_safe_query(sql)
            return {
                "success": sql_result.get("success", False) or rag_result.get("success", False),
                "intent": intent,
                "tool_used": "SQL + RAG (Combined)",
                "data": sql_result.get("data"),
                "sql_used": sql_result.get("sql_used"),
                "rag_chunks": rag_result.get("chunks"),
                "sql_error": sql_result.get("error"),
            }
        else:
            rag_result["tool_used"] = "Documentation RAG (Combined)"
            rag_result["intent"] = "RAG_KNOWLEDGE"
            return rag_result
            
    # ─── CASUAL_GREETING ───────────────────────────────────────────────────
    elif intent == "CASUAL_GREETING":
         return {
             "success": True, 
             "data": "A casual greeting was detected.",
             "tool_used": "None",
             "intent": intent
         }

    # ─── UNSUPPORTED_QUERY ─────────────────────────────────────────────────
    elif intent == "UNSUPPORTED_QUERY":
         # Fallback to RAG if query mentions any mobility terms
         q_lower = original_query.lower()
         if any(w in q_lower for w in ["taxi", "traffic", "ride", "trip", "fare", "zone", "manhattan", "speed", "model", "audit", "anomaly", "report", "predict", "hour", "rush", "volume", "borough"]):
             result = rag_service.retrieve_knowledge(original_query)
             result["tool_used"] = "Documentation RAG"
             result["intent"] = "RAG_KNOWLEDGE"
             return result
             
         return {
             "success": False,
             "error": "This question is outside the scope of the Urban Flow Analytics project.",
             "tool_used": "None",
             "intent": intent
         }
         
    return {"success": False, "error": f"Unknown intent: {intent}"}
